export const FORM_DATA_MAPPING = {
  area: "Built up area (Sqft)",
  front: "Front (Ft)",
  sold: "Status",
  location: "Address",
  plot_name: "Plot Number",
  colony: "Colony",
  pincode: "Pincode",
  landmark: "Landmark",
  floor: "Total Floors",
  room: "Total Rooms",
  hall: "Total Halls",
  parking: "Total Parkings",
  covered_parking: "Parking Type",
  outer_staircase: "Staircase Type",
  bathroom: "Bathrooms",
  attached_bathroom: "Attached Bathrooms",
  common_bathroom: "Common Btahrooms",
  other_specification: "Other Specifications",
};
